apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: opentelemetry
    namespace: observability
spec:
    interval: 24h
    url: https://open-telemetry.github.io/opentelemetry-helm-charts
