apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
    name: ejbca-postgres
    namespace: ejbca
spec:
    selector:
        matchLabels:
            cnpg.io/cluster: ejbca-postgres
    podMetricsEndpoints:
        - port: metrics
