apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
    name: ceph-cluster
    namespace: rook-ceph
spec:
    dataDirHostPath: /var/lib/rook
    cephVersion:
        image: quay.io/ceph/ceph:v20.2.0
        allowUnsupported: false
    mon:
        count: 1
        allowMultiplePerNode: true
    skipUpgradeChecks: false
    mgr:
        count: 1
        allowMultiplePerNode: true
        modules:
            - name: rook
              enabled: true
    dashboard:
        enabled: true
    crashCollector:
        disable: true
    storage:
        useAllNodes: false
        useAllDevices: false
        nodes:
            - name: "axiom-vm-k8s-master"
              devices:
                  - name: "/dev/sdb"
        allowDeviceClassUpdate: true
        allowOsdCrushWeightUpdate: false
    monitoring:
        enabled: false
    healthCheck:
        daemonHealth:
            mon:
                interval: 45s
                timeout: 600s
    priorityClassNames:
        all: system-node-critical
        mgr: system-cluster-critical
    disruptionManagement:
        managePodBudgets: true
    cephConfig:
        global:
            osd_pool_default_size: "1"
            mon_warn_on_pool_no_redundancy: "false"
            bdev_flock_retry: "20"
            bluefs_buffered_io: "false"
            mon_data_avail_warn: "10"
