apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
    name: ceph-cluster
    namespace: rook-ceph
spec:
    cephVersion:
        image: quay.io/ceph/ceph:v18.2.1
        allowUnsupported: false
    dataDirHostPath: /var/lib/rook
    skipUpgradeChecks: false
    continueUpgradeAfterChecksEvenIfNotHealthy: false
    waitTimeoutForHealthyOSDInMinutes: 10
    mon:
        count: 1
        allowMultiplePerNode: false
    mgr:
        count: 1
        allowMultiplePerNode: false
        modules:
            - name: pg_autoscaler
              enabled: true
    dashboard:
        enabled: true
        ssl: true
    monitoring:
        enabled: false
    network:
        connections:
            encryption:
                enabled: false
            compression:
                enabled: false
    crashCollector:
        disable: false
    logCollector:
        enabled: false
    cleanupPolicy:
        confirmation: ""
        sanitizeDisks:
            method: quick
            dataSource: zero
            iteration: 1
        allowUninstallWithVolumes: false
    removeOSDsIfOutAndSafeToRemove: false
    priorityClassNames:
        mon: system-node-critical
        osd: system-node-critical
        mgr: system-cluster-critical
    storage:
        useAllNodes: false
        useAllDevices: false
        nodes:
            - name: "axiom-vm-k8s-master"
              devices:
                  - name: "/dev/sdb"
    disruptionManagement:
        managePodBudgets: true
        osdMaintenanceTimeout: 30
        pgHealthCheckTimeout: 0
    healthCheck:
        daemonHealth:
            mon:
                disabled: false
                interval: 45s
            osd:
                disabled: false
                interval: 60s
            status:
                disabled: false
                interval: 60s
        livenessProbe:
            mon:
                disabled: false
            mgr:
                disabled: false
            osd:
                disabled: false
    resources:
        mon:
            limits:
                memory: "1Gi"
            requests:
                cpu: "500m"
                memory: "512Mi"
        mgr:
            limits:
                memory: "1Gi"
            requests:
                cpu: "500m"
                memory: "512Mi"
        osd:
            limits:
                memory: "2Gi"
            requests:
                cpu: "500m"
                memory: "1Gi"
        prepareosd:
            limits:
                memory: "1Gi"
            requests:
                cpu: "250m"
                memory: "512Mi"
