apiVersion: v1
kind: Secret
metadata:
    name: davmail-cert-pkcs12-password
    namespace: davmail
stringData:
    # incredibly bad practice to store secrets in a publicly available repository
    # but it's just for something that should already be secret (Kubernetes secrets)
    password: Accordingtoallknownlawsofaviationthereisnowaythatabeeshouldbeabletofly
