apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - namespace.yaml
    - service.yaml
    - service-alt.yaml
    - statefulset.yaml
    - httproute.yaml
    - certificate.yaml
    - certificate-secret.yaml
