apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: woodpecker
    namespace: woodpecker
spec:
    interval: 30m
    chartRef:
        kind: OCIRepository
        name: woodpecker
        namespace: woodpecker
    install:
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
        agent:
            enabled: false
        server:
            env:
                WOODPECKER_HOST: "https://woodpecker.internal.axiom.lucasfehres.nl"
                WOODPECKER_FORGEJO: "true"
                WOODPECKER_FORGEJO_URL: "https://forgejo.axiom.lucasfehres.nl"
                WOODPECKER_OPEN: "false"
                WOODPECKER_ADMIN: lucasf
            extraSecretNamesForEnvFrom:
                - axiom-forgejo
            persistentVolume:
                size: 4Gi
                storageClass: rook-ceph-block
            ingress:
                enabled: true
                ingressClassName: tailscale
                hosts: []
                tls:
                    hosts:
                        - woodpecker-server
