apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
    name: tls-gateway
    namespace: kube-system
    annotations:
        cert-manager.io/issuer: letsencrypt
spec:
    gatewayClassName: cilium
    listeners:
        - name: https
          protocol: HTTPS
          port: 443
          hostname: "*.axiom.lucasfehres.nl"
          tls:
              certificateRefs:
                  - kind: Secret
                    name: ca
