apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
    name: insecure-gateway
    namespace: kube-system
spec:
    gatewayClassName: cilium
    addresses:
        - type: IPAddress
          # axiom-vm-k8s-master
          value: "10.67.1.103"
    listeners:
        - protocol: HTTP
          port: 80
          name: insecure
          allowedRoutes:
              # TODO: specify ONLY cert-manager
              namespaces:
                  from: Same
