apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: woodpecker-agent
    namespace: woodpecker-agent
spec:
    interval: 30m
    chartRef:
        kind: OCIRepository
        name: woodpecker
        namespace: woodpecker-agent
    install:
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
        agent:
            enabled: true
            replicaCount: 1
            env:
                # WOODPECKER_SERVER: "https://woodpecker.internal.axiom.lucasfehres.nl"
                # referenced internally over Tailscale
                WOODPECKER_SERVER: "woodpecker-server-ts:9000"
                # for use on Rackspace
                WOODPECKER_BACKEND_K8S_STORAGE_CLASS: ssd
                WOODPECKER_BACKEND_K8S_NAMESPACE: woodpecker-agent
                WOODPECKER_MAX_WORKFLOWS: "16"
            extraSecretNamesForEnvFrom:
                - axiom-woodpecker
            persistence:
                enabled: false
        server:
            enabled: false
