apiVersion: authentication.liqo.io/v1beta1
kind: Tenant
metadata:
    labels:
        liqo.io/remote-cluster-id: axiom
    name: axiom
    namespace: liqo-tenant-axiom
spec:
    clusterID: axiom
    authzPolicy: TolerateNoHandshake
    tenantCondition: Active
