apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: external-forgejo
    namespace: forgejo
spec:
    parentRefs:
        # has to be to the public internet unfortunately do to issues having Woodpecker pods in
        # us-east-iad-1-1 accessing Forgejo.
        - name: tls-gateway
          namespace: kube-system
    hostnames:
        - "forgejo.axiom.lucasfehres.nl"
    rules:
        - backendRefs:
              - name: external-forgejo
                port: 3000
