apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
    name: jira-postgres
    namespace: atlassian
spec:
    selector:
        matchLabels:
            cnpg.io/cluster: jira-postgres
    podMetricsEndpoints:
        - port: metrics
