apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
    name: jira-postgres
    namespace: atlassian
spec:
    cluster:
        name: jira-postgres
    # midnight every day
    schedule: "0 0 0 * * *"
    backupOwnerReference: self
    method: plugin
    pluginConfiguration:
        name: barman-cloud.cloudnative-pg.io
