apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
    name: authentik-postgres
    namespace: authentik
spec:
    instances: 3
    storage:
        storageClass: rook-ceph-block
        size: 1Gi

    # makes sure archives to S3 happen even if not that much data was touched in the DB
    postgresql:
        parameters:
            archive_timeout: "15min"

    plugins:
        - name: barman-cloud.cloudnative-pg.io
          isWALArchiver: true
          parameters:
              barmanObjectName: authentik-postgres

        # - name: barman-cloud.cloudnative-pg.io
        #   isWALArchiver: false
        #   parameters:
        #       barmanObjectName: authentik-postgres-b2
