apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
    name: authentik-postgres
    namespace: authentik
spec:
    instances: 3
    storage:
        storageClass: rook-ceph-block
        size: 1Gi
