apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
    name: authentik-postgres
    namespace: authentik
spec:
    selector:
        matchLabels:
            cnpg.io/cluster: authentik-postgres
    podMetricsEndpoints:
        - port: metrics
