apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: shared-infrastructure-tailscale
    namespace: flux-system
spec:
    interval: 10m
    sourceRef:
        kind: GitRepository
        name: flux-system
    path: ./flux/shared-infrastructure/tailscale
    prune: true
    wait: true
    timeout: 10m
