apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
    name: harbor-postgres
    namespace: harbor
spec:
    instances: 1
    storage:
        storageClass: rook-ceph-block
        size: 1Gi

    managed:
        services:
            additional:
                - selectorType: rw
                  serviceTemplate:
                      metadata:
                          name: "harbor-postgres-lb"
                      spec:
                          type: LoadBalancer

    plugins:
        - name: barman-cloud.cloudnative-pg.io
          isWALArchiver: true
          parameters:
              barmanObjectName: harbor-postgres

        # - name: barman-cloud.cloudnative-pg.io
        #   isWALArchiver: false
        #   parameters:
        #       barmanObjectName: harbor-postgres-b2
