apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
    name: harbor-postgres
    namespace: harbor
spec:
    selector:
        matchLabels:
            cnpg.io/cluster: harbor-postgres
    podMetricsEndpoints:
        - port: metrics
