apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: liqo
    namespace: liqo
spec:
    interval: 30m
    chart:
        spec:
            chart: liqo
            # the 1.1.1 release has an issue where firewall rules are applied endlessly, consuming an entire CPU
            # core 24/7. with these logs on repeat
            # I0225 21:28:58.982159       1 firewallconfiguration_controller.go:159] Applied firewallconfiguration liqo/gw-mss-clamping
            # I0225 21:28:58.986486       1 firewallconfiguration_controller.go:159] Applied firewallconfiguration liqo/service-nodeport-routing
            # I0225 21:28:58.992054       1 firewallconfiguration_controller.go:159] Applied firewallconfiguration liqo-tenant-chaos-2/chaos-2-remap-externalcidr
            # I0225 21:28:58.996639       1 firewallconfiguration_controller.go:159] Applied firewallconfiguration liqo-tenant-chaos-2/chaos-2-remap-podcidr
            # I0225 21:28:59.000736       1 firewallconfiguration_controller.go:159] Applied firewallconfiguration liqo-tenant-chaos-2/chaos-2-unknown-source-remap-ipmapping-gw
            # I0225 21:28:59.010639       1 firewallconfiguration_controller.go:159] Applied firewallconfiguration liqo/api-server-proxy-remap-ipmapping-gw
            # I0225 21:28:59.024074       1 firewallconfiguration_controller.go:159] Applied firewallconfiguration liqo/api-server-remap-ipmapping-gw
            # I0225 21:28:59.029704       1 netmonitor.go:269] Nftables rule removed: mss-clamping-out
            # Liqo has been temporarily downgraded because of this issue.
            version: "1.0.3"
            sourceRef:
                kind: HelmRepository
                name: liqo
                namespace: liqo
            interval: 12h
    install:
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
        # TODO: schedule downtime and put some limits on the gw-server and gw-client. There is a bug
        # where it may loop when applying firewall configurations, using 700 mCPU.

        # cilium !
        ipam:
            # Cilium uses per-node CIDRs, but this encompasses all of 'em
            podCIDR: 10.42.0.0/16
            serviceCIDR: 10.43.0.0/16
            reservedSubnets:
                - 10.67.0.0/16
                - 192.168.0.0/16

        apiServer:
            address: "https://ds01.fsn1.hw.axiom.lucasfehres.nl:6443"

        metrics:
            enabled: true
            prometheusOperator:
                enabled: true

        offloading:
            reflection:
                service:
                    type: AllowList

        discovery:
            config:
                clusterID: axiom
