apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
    name: gitlab-postgres
    namespace: gitlab
spec:
    instances: 1
    storage:
        storageClass: rook-ceph-block
        size: 2Gi

        # TODO: username gitlab

    # BACKUP RESTORE
    # bootstrap:
    #     recovery:
    #         source: gitlab-postgres

    # externalClusters:
    #     - name: gitlab-postgres
    #       plugin:
    #           name: barman-cloud.cloudnative-pg.io
    #           parameters:
    #               barmanObjectName: gitlab-postgres

    # makes sure archives to S3 happen even if not that much data was touched in the DB
    postgresql:
        parameters:
            archive_timeout: "15min"

    plugins:
        - name: barman-cloud.cloudnative-pg.io
          isWALArchiver: true
          parameters:
              barmanObjectName: gitlab-postgres

    # - name: barman-cloud.cloudnative-pg.io
    #   isWALArchiver: false
    #   parameters:
    #       barmanObjectName: gitlab-postgres-b2
