apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: fluent-bit
    namespace: observability
spec:
    interval: 30m
    chart:
        spec:
            chart: fluent-bit
            version: "0.57.6"
            sourceRef:
                kind: HelmRepository
                name: fluent-bit
                namespace: observability
            interval: 12h
    install:
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
        config:
            # Filtering is necessary because the Rook pods exceed the max amount of labels
            filters: |
                [FILTER]
                    Name kubernetes
                    Match kube.*
                    Merge_Log On
                    Keep_Log Off
                    K8S-Logging.Parser On
                    K8S-Logging.Exclude On

                [FILTER]
                    Name        lua
                    Match       kube.*
                    Script      /fluent-bit/lua-scripts/k8s.lua
                    Call alter_fields

            outputs: |
                [OUTPUT]
                    Name                    loki
                    Match                   kube.*

                    Host                    loki-write.internal.axiom.lucasfehres.nl
                    Port                    443
                    Tls                     on
                    Tls.verify              on

                    Labels                  job=kube-fluentbit
                    Auto_Kubernetes_Labels  on
        serviceMonitor:
            enabled: true
        dashboards:
            enabled: true

        daemonSetVolumes:
            - name: lua-scripts
              configMap:
                  name: fluent-bit-lua-scripts
        daemonSetVolumeMounts:
            - name: lua-scripts
              mountPath: /fluent-bit/lua-scripts
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: fluent-bit-lua-scripts
    namespace: observability
data:
    k8s.lua: |
        function alter_fields(tag, timestamp, record)
            record["kubernetes"]["labels"]["rook_io_operator_namespace"] = nil
            record["kubernetes"]["labels"]["rook_cluster"] = nil
            record["kubernetes"]["labels"]["mon_cluster"] = nil
            record["kubernetes"]["labels"]["mon_daemon"] = nil

            return 1, timestamp, record
        end
