apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: freshrss
    namespace: freshrss
spec:
    interval: 30m
    chart:
        spec:
            chart: freshrss
            version: "2.12.4"
            sourceRef:
                kind: HelmRepository
                name: freshrss
                namespace: freshrss
            interval: 12h
    install:
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
        freshrss:
            baseUrl: "https://freshrss.internal.axiom.lucasfehres.nl"
            timezone: "Europe/Amsterdam"
            database:
                type: postgresql
            initialization:
                enabled: false
                admin:
                    email: "lucasfehres@gmail.com"
                    # o_o
                    # no longer valid btw
                    password: "verysecurepassword"
                    username: lucasf
            persistence:
                data:
                    size: 1Gi
                extensions:
                    size: 1Gi
                storageClass: rook-ceph-block

        externalPostgresql:
            auth:
                database: app
                username: app
                # very very bad practice but the DB shouldn't be accessible from the internet
                # and I'm not putting in the effort to fix the vibed Helm chart.
                password: xoEC4e3Uh90kDFeI60rj3jUbkHHgQZeQx9SDAfOcHbE7iMtoMELSstKqMAslOZW5
            hostname: freshrss-postgres-rw
