apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: apps-personal-zerotier
    namespace: flux-system
spec:
    dependsOn:
        - name: apps-personal-zerotier-postgres
    interval: 10m
    sourceRef:
        kind: GitRepository
        name: flux-system
    path: ./flux/apps/utilities/zerotier
    prune: true
    wait: true
    timeout: 10m
