apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: apps-utilities-iperf3-axiom
    namespace: flux-system
spec:
    interval: 10m
    sourceRef:
        kind: GitRepository
        name: flux-system
    path: ./flux/apps/utilities/iperf3/axiom
    prune: true
    wait: true
    timeout: 10m
