apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: infrastructure-observability-offloading
    namespace: flux-system
spec:
    interval: 10m
    sourceRef:
        kind: GitRepository
        name: flux-system
    path: ./flux/infrastructure/observability/observability-offloading
    prune: true
    wait: true
    timeout: 10m
