apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    # DO NOT TOUCH!
    name: infrastructure-rook-ceph
    namespace: flux-system
spec:
    dependsOn:
        # cluster won't deploy if the Prometheus types don't exist
        - name: infrastructure-observability
    interval: 10m
    sourceRef:
        kind: GitRepository
        name: flux-system
    path: ./flux/infrastructure/rook-ceph
    # DO NOT PRUNE CEPH
    prune: false
    wait: true
    timeout: 10m
