apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: infrastructure-rook-ceph
    namespace: flux-system
spec:
    interval: 10m
    sourceRef:
        kind: GitRepository
        name: flux-system
    path: ./flux/infrastructure/rook-ceph
    # DO NOT PRUNE CEPH
    prune: false
    wait: true
    timeout: 10m
