apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: rook-ceph
    namespace: rook-ceph
spec:
    interval: 30m
    chart:
        spec:
            chart: rook-ceph
            version: ">=1.12.0 <2.0.0" # Pin to a range
            sourceRef:
                kind: HelmRepository
                name: rook-release
                namespace: rook-ceph
            interval: 12h
    install:
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
        authentik:
            # TODO: postgresql SSL
            postgresql:
                host: file:///secrets/postgres-app/host
                port: file:///secrets/postgres-app/port
                name: file:///secrets/postgres-app/dbname
                user: file:///secrets/postgres-app/password
                password: file:///secrets/postgres-app/user

            # Secret key - generate with: openssl rand -base64 32
            secret_key: file:///secrets/axiom/secret-key

        route:
            main:
                enabled: true
                parentRefs:
                    - name: tls-gateway
                      namespace: kube-system
                hostnames:
                    - "authentik.axiom.lucasfehres.nl"

        server:
            volumes:
                - name: postgres-app-secret
                  secret:
                      secretName: authentik-postgres-app
                      optional: false
                - name: postgres-server-secret
                  secret:
                      secretName: authentik-postgres-server
                      optional: false
                - name: axiom-authentik-secrets
                  secret:
                      secretName: axiom-authentik-secrets
                      optional: false

            volumeMounts:
                - name: postgres-app-secret
                  mountPath: /secrets/postgres-app
                  readOnly: true
                - name: postgres-server-secret
                  mountPath: /secrets/postgres-server
                  readOnly: true
                - name: axiom-authentik-secrets
                  mountPath: /secrets/axiom
                  readOnly: true

        worker:
            volumes:
                - name: postgres-app-secret
                  secret:
                      secretName: authentik-postgres-app
                      optional: false
                - name: postgres-server-secret
                  secret:
                      secretName: authentik-postgres-server
                      optional: false
                - name: axiom-authentik-secrets
                  secret:
                      secretName: axiom-authentik-secrets
                      optional: false

            volumeMounts:
                - name: postgres-app-secret
                  mountPath: /secrets/postgres-app
                  readOnly: true
                - name: postgres-server-secret
                  mountPath: /secrets/postgres-server
                  readOnly: true
                - name: axiom-authentik-secrets
                  mountPath: /secrets/axiom
                  readOnly: true
