apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
    name: vaultwarden-postgres
    namespace: vaultwarden
spec:
    instances: 3
    storage:
        storageClass: rook-ceph-block
        size: 500Mi
