apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
    name: vaultwarden-postgres
    namespace: vaultwarden
spec:
    selector:
        matchLabels:
            cnpg.io/cluster: vaultwarden-postgres
    podMetricsEndpoints:
        - port: metrics
