apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt
spec:
    acme:
        solvers:
            - http01:
                  gatewayHTTPRoute:
                      parentRefs:
                          - name: insecure-gateway
                            namespace: kube-system
                            kind: Gateway
