apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
    name: basic-collector
    namespace: observability
spec:
    config:
        receivers:
            otlp:
                protocols:
                    grpc:
                        endpoint: 0.0.0.0:4317
                    http:
                        endpoint: 0.0.0.0:4318
        processors:
            memory_limiter:
                check_interval: 1s
                limit_percentage: 75
                spike_limit_percentage: 15

        exporters:
            prometheus:
                endpoint: "0.0.0.0:9464"

        service:
            pipelines:
                metrics:
                    receivers: [otlp]
                    processors: [memory_limiter]
                    exporters: [prometheus]
