apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
    name: basic-collector
    namespace: observability
spec:
    selector:
        matchLabels:
            kustomize.toolkit.fluxcd.io/name: infrastructure-opentelemetry-collector
    podMetricsEndpoints:
        - port: prometheus
