apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: cnpg-barman
    namespace: cnpg-system
spec:
    interval: 30m
    chart:
        spec:
            chart: plugin-barman-cloud
            version: "0.5.0"
            sourceRef:
                kind: HelmRepository
                name: cnpg
                namespace: cnpg-system
            interval: 12h
    install:
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
