apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: external-dns
    namespace: kube-system
spec:
    interval: 30m
    chart:
        spec:
            chart: external-dns
            version: "1.20.0"
            sourceRef:
                kind: HelmRepository
                name: external-dns
                namespace: kube-system
            interval: 12h
    install:
        crds: CreateReplace
        remediation:
            retries: 3
    upgrade:
        crds: CreateReplace
        remediation:
            retries: 3
    values:
        provider:
            name: cloudflare
        env:
            - name: CF_API_TOKEN
              valueFrom:
                  secretKeyRef:
                      name: axiom-cloudflare-api-key
                      key: apiKey

        serviceMonitor:
            enabled: true
