apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
    name: thanos-bitnami
    namespace: observability
spec:
    interval: 24h
    url: oci://registry-1.docker.io/bitnamicharts/thanos
    ref:
        tag: 17.3.1
