apiVersion: v1
kind: Service
metadata:
    annotations:
        tailscale.com/tailnet-fqdn: thanos-us-east-iad-1-1.tail5694a.ts.net
    name: thanos-us-east-iad-1-1
    namespace: observability
spec:
    externalName: placeholder
    type: ExternalName
