apiVersion: v1
kind: ConfigMap
metadata:
    name: well-known-files
    namespace: well-known
data:
    atproto-did: did:plc:y2dhgjku4yviuzyzftv5ilqf
    pgp.asc: |
        -----BEGIN PGP PUBLIC KEY BLOCK-----

        mDMEaa3YNhYJKwYBBAHaRw8BAQdAf6lvmCp7oct/P47UmxTE59OmYzPdFTkVBhRn
        tQIaSzu0JEx1Y2FzIEZlaHJlcyA8bHVjYXNmZWhyZXNAZ21haWwuY29tPoiZBBMW
        CgBBAhsDBQkFo5qABQsJCAcCBhUKCQgLAgQWAgMBAh4BAheAFiEE2/S6VTi/RVXj
        6FSOj28JNuOdnQ4FAmmt2TsCGQEACgkQj28JNuOdnQ5RswD+Oiz8hfy5xDtOn8SB
        T31+FLFSOM0RhYtkgaBq8kPpP+4A/0vC5+nFOTmQp5/bTUTL9oASFo9M0xTSKNSy
        3KmbT5sKtD9MdWNhcyBGZWhyZXMgKFNlY29uZGFyeSBlbWFpbCBhZGRyZXNzKSA8
        bHVjYXNmZWhyZXNAaWNsb3VkLmNvbT6IlgQTFgoAPhYhBNv0ulU4v0VV4+hUjo9v
        CTbjnZ0OBQJprdiWAhsDBQkFo5qABQsJCAcCBhUKCQgLAgQWAgMBAh4BAheAAAoJ
        EI9vCTbjnZ0O3R0BAKWeZgj/MR8MKfI9YKiNp5cGTSvOSfYwrLKSy+jTbtfaAP9W
        7WMBOMCPj/d6znvZBUFP0pAoMMc3shGWmc6l28JpDbQ+THVjYXMgRmVocmVzIChT
        dHVkZW50IGVtYWlsIGFkZHJlc3MpIDxsbWZlaHJlc0BzdHVkZW50LmNoZS5ubD6I
        lgQTFgoAPhYhBNv0ulU4v0VV4+hUjo9vCTbjnZ0OBQJprdzoAhsDBQkFo5qABQsJ
        CAcCBhUKCQgLAgQWAgMBAh4BAheAAAoJEI9vCTbjnZ0OT4EA/i9e7phzQb863cgc
        K2h/qtzyDOolSQZUSCearO4TgsEvAPsFSmzUjv1ZKT6NkLgwY/HvzFDDnbEYfdPg
        dvxbRdzvCLg4BGmt2DYSCisGAQQBl1UBBQEBB0BDp2C54f/9UBDYMCsKB3UpwYPw
        /yaGDMaXJvCGrd/AOwMBCAeIfgQYFgoAJhYhBNv0ulU4v0VV4+hUjo9vCTbjnZ0O
        BQJprdg2AhsMBQkFo5qAAAoJEI9vCTbjnZ0O1y8A/RZLhLXZDs8MeNkoRMqwMNmE
        uGXIOm9ZpqZOx7VfiEkwAP419S1CV97lZIavWF6G5J/PArcCHcy4oPW976f7yeec
        Aw==
        =5QWC
        -----END PGP PUBLIC KEY BLOCK-----
    pgp-key.txt: |
        -----BEGIN PGP PUBLIC KEY BLOCK-----

        mDMEaa3YNhYJKwYBBAHaRw8BAQdAf6lvmCp7oct/P47UmxTE59OmYzPdFTkVBhRn
        tQIaSzu0JEx1Y2FzIEZlaHJlcyA8bHVjYXNmZWhyZXNAZ21haWwuY29tPoiZBBMW
        CgBBAhsDBQkFo5qABQsJCAcCBhUKCQgLAgQWAgMBAh4BAheAFiEE2/S6VTi/RVXj
        6FSOj28JNuOdnQ4FAmmt2TsCGQEACgkQj28JNuOdnQ5RswD+Oiz8hfy5xDtOn8SB
        T31+FLFSOM0RhYtkgaBq8kPpP+4A/0vC5+nFOTmQp5/bTUTL9oASFo9M0xTSKNSy
        3KmbT5sKtD9MdWNhcyBGZWhyZXMgKFNlY29uZGFyeSBlbWFpbCBhZGRyZXNzKSA8
        bHVjYXNmZWhyZXNAaWNsb3VkLmNvbT6IlgQTFgoAPhYhBNv0ulU4v0VV4+hUjo9v
        CTbjnZ0OBQJprdiWAhsDBQkFo5qABQsJCAcCBhUKCQgLAgQWAgMBAh4BAheAAAoJ
        EI9vCTbjnZ0O3R0BAKWeZgj/MR8MKfI9YKiNp5cGTSvOSfYwrLKSy+jTbtfaAP9W
        7WMBOMCPj/d6znvZBUFP0pAoMMc3shGWmc6l28JpDbQ+THVjYXMgRmVocmVzIChT
        dHVkZW50IGVtYWlsIGFkZHJlc3MpIDxsbWZlaHJlc0BzdHVkZW50LmNoZS5ubD6I
        lgQTFgoAPhYhBNv0ulU4v0VV4+hUjo9vCTbjnZ0OBQJprdzoAhsDBQkFo5qABQsJ
        CAcCBhUKCQgLAgQWAgMBAh4BAheAAAoJEI9vCTbjnZ0OT4EA/i9e7phzQb863cgc
        K2h/qtzyDOolSQZUSCearO4TgsEvAPsFSmzUjv1ZKT6NkLgwY/HvzFDDnbEYfdPg
        dvxbRdzvCLg4BGmt2DYSCisGAQQBl1UBBQEBB0BDp2C54f/9UBDYMCsKB3UpwYPw
        /yaGDMaXJvCGrd/AOwMBCAeIfgQYFgoAJhYhBNv0ulU4v0VV4+hUjo9vCTbjnZ0O
        BQJprdg2AhsMBQkFo5qAAAoJEI9vCTbjnZ0O1y8A/RZLhLXZDs8MeNkoRMqwMNmE
        uGXIOm9ZpqZOx7VfiEkwAP419S1CV97lZIavWF6G5J/PArcCHcy4oPW976f7yeec
        Aw==
        =5QWC
        -----END PGP PUBLIC KEY BLOCK-----
