apiVersion: v1
kind: ConfigMap
metadata:
    name: well-known-files
    namespace: well-known
data:
    atproto-did: did:plc:y2dhgjku4yviuzyzftv5ilqf
    discord: dh=8de898afd3bf117c7e01b213fabbb717d6eef981
    pgp.asc: |
        -----BEGIN PGP PUBLIC KEY BLOCK-----

        mDMEaa3YNhYJKwYBBAHaRw8BAQdAf6lvmCp7oct/P47UmxTE59OmYzPdFTkVBhRn
        tQIaSzu0JEx1Y2FzIEZlaHJlcyA8bHVjYXNmZWhyZXNAZ21haWwuY29tPoiTBBMW
        CgA7AhsDBQsJCAcCBhUKCQgLAgQWAgMBAh4BAheAAhkBFiEE2/S6VTi/RVXj6FSO
        j28JNuOdnQ4FAmmuz8AACgkQj28JNuOdnQ46uwEA3+dLGp0SbI7jCX6jbcdTyihE
        HxDRT7SQaaB9vpgHEqcBAIiBZLEqKWDse92F+WBMS+dmFYJGZCi5qEAkwy8WDSIN
        tD9MdWNhcyBGZWhyZXMgKFNlY29uZGFyeSBlbWFpbCBhZGRyZXNzKSA8bHVjYXNm
        ZWhyZXNAaWNsb3VkLmNvbT6IkAQTFgoAOAIbAwULCQgHAgYVCgkICwIEFgIDAQIe
        AQIXgBYhBNv0ulU4v0VV4+hUjo9vCTbjnZ0OBQJprs/FAAoJEI9vCTbjnZ0OGM0B
        APUrHr0HdRSlODWU8CMmYc3mg6CWTM5G+ZHYYGNdRM1+AP0RsXelWWVE2jR2hDJZ
        kImByvXKtZLljm+SIqyPqrjwBrQ+THVjYXMgRmVocmVzIChTdHVkZW50IGVtYWls
        IGFkZHJlc3MpIDxsbWZlaHJlc0BzdHVkZW50LmNoZS5ubD6IkAQTFgoAOAIbAwUL
        CQgHAgYVCgkICwIEFgIDAQIeAQIXgBYhBNv0ulU4v0VV4+hUjo9vCTbjnZ0OBQJp
        rs/LAAoJEI9vCTbjnZ0OwWMBAI1xMGYFBB07RElyB3oOTpg5fXPIvtHC+gRSNhMN
        7TR2AQDd2zC0rLopIf3L8lw+iGNORI6U+PbRGZIw3BwdbmXFCbg4BGmt2DYSCisG
        AQQBl1UBBQEBB0BDp2C54f/9UBDYMCsKB3UpwYPw/yaGDMaXJvCGrd/AOwMBCAeI
        fgQYFgoAJhYhBNv0ulU4v0VV4+hUjo9vCTbjnZ0OBQJprdg2AhsMBQkFo5qAAAoJ
        EI9vCTbjnZ0O1y8A/RZLhLXZDs8MeNkoRMqwMNmEuGXIOm9ZpqZOx7VfiEkwAP41
        9S1CV97lZIavWF6G5J/PArcCHcy4oPW976f7yeecA7gzBGmuzygWCSsGAQQB2kcP
        AQEHQI7DuN2sdudDH8sRRfeDXpDq07qgb8t14x1+seO1fcz1iPUEGBYKACYWIQTb
        9LpVOL9FVePoVI6Pbwk2452dDgUCaa7PKAIbAgUJAeBjyACBCRCPbwk2452dDnYg
        BBkWCgAdFiEEgjkPJy2ATdHpddKC1qB6cAOTYswFAmmuzygACgkQ1qB6cAOTYszB
        YAEAtAF96Pp6IQdKwX5yaWSm8w54vwwjQ0jlIHEpXJUJyvcBAKEqBqly45kj0bDK
        h8lZVz07j6EpKYUZyGEkIQ4s8tID6MsBAK1IV1XPzNzpeanwPtUqRZojiUuMYnR6
        cSS8ckWXp/EQAP4t6x/pSPtsMSJ0k/kNrKC70KfVlJFIEnZjbZA17ue8ALgzBGmu
        0WAWCSsGAQQB2kcPAQEHQBxpkLVz4yvM7io7W+4Xo7Y86hD1srAdR9nHF1NIoMU8
        iH4EGBYKACYWIQTb9LpVOL9FVePoVI6Pbwk2452dDgUCaa7RYAIbIAUJAeBhkAAK
        CRCPbwk2452dDud/AP9muWh2fNzF3yDDUtT2Wk1YjqqXemxWRU/47leyzoDykgEA
        +DPyJlSs/mqGuZ/wsVFsn3Nuy3D/KWBrzc6Kp0bd2Ag=
        =qSSq
        -----END PGP PUBLIC KEY BLOCK-----
    pgp-key.txt: |
        -----BEGIN PGP PUBLIC KEY BLOCK-----

        mDMEaa3YNhYJKwYBBAHaRw8BAQdAf6lvmCp7oct/P47UmxTE59OmYzPdFTkVBhRn
        tQIaSzu0JEx1Y2FzIEZlaHJlcyA8bHVjYXNmZWhyZXNAZ21haWwuY29tPoiTBBMW
        CgA7AhsDBQsJCAcCBhUKCQgLAgQWAgMBAh4BAheAAhkBFiEE2/S6VTi/RVXj6FSO
        j28JNuOdnQ4FAmmuz8AACgkQj28JNuOdnQ46uwEA3+dLGp0SbI7jCX6jbcdTyihE
        HxDRT7SQaaB9vpgHEqcBAIiBZLEqKWDse92F+WBMS+dmFYJGZCi5qEAkwy8WDSIN
        tD9MdWNhcyBGZWhyZXMgKFNlY29uZGFyeSBlbWFpbCBhZGRyZXNzKSA8bHVjYXNm
        ZWhyZXNAaWNsb3VkLmNvbT6IkAQTFgoAOAIbAwULCQgHAgYVCgkICwIEFgIDAQIe
        AQIXgBYhBNv0ulU4v0VV4+hUjo9vCTbjnZ0OBQJprs/FAAoJEI9vCTbjnZ0OGM0B
        APUrHr0HdRSlODWU8CMmYc3mg6CWTM5G+ZHYYGNdRM1+AP0RsXelWWVE2jR2hDJZ
        kImByvXKtZLljm+SIqyPqrjwBrQ+THVjYXMgRmVocmVzIChTdHVkZW50IGVtYWls
        IGFkZHJlc3MpIDxsbWZlaHJlc0BzdHVkZW50LmNoZS5ubD6IkAQTFgoAOAIbAwUL
        CQgHAgYVCgkICwIEFgIDAQIeAQIXgBYhBNv0ulU4v0VV4+hUjo9vCTbjnZ0OBQJp
        rs/LAAoJEI9vCTbjnZ0OwWMBAI1xMGYFBB07RElyB3oOTpg5fXPIvtHC+gRSNhMN
        7TR2AQDd2zC0rLopIf3L8lw+iGNORI6U+PbRGZIw3BwdbmXFCbg4BGmt2DYSCisG
        AQQBl1UBBQEBB0BDp2C54f/9UBDYMCsKB3UpwYPw/yaGDMaXJvCGrd/AOwMBCAeI
        fgQYFgoAJhYhBNv0ulU4v0VV4+hUjo9vCTbjnZ0OBQJprdg2AhsMBQkFo5qAAAoJ
        EI9vCTbjnZ0O1y8A/RZLhLXZDs8MeNkoRMqwMNmEuGXIOm9ZpqZOx7VfiEkwAP41
        9S1CV97lZIavWF6G5J/PArcCHcy4oPW976f7yeecA7gzBGmuzygWCSsGAQQB2kcP
        AQEHQI7DuN2sdudDH8sRRfeDXpDq07qgb8t14x1+seO1fcz1iPUEGBYKACYWIQTb
        9LpVOL9FVePoVI6Pbwk2452dDgUCaa7PKAIbAgUJAeBjyACBCRCPbwk2452dDnYg
        BBkWCgAdFiEEgjkPJy2ATdHpddKC1qB6cAOTYswFAmmuzygACgkQ1qB6cAOTYszB
        YAEAtAF96Pp6IQdKwX5yaWSm8w54vwwjQ0jlIHEpXJUJyvcBAKEqBqly45kj0bDK
        h8lZVz07j6EpKYUZyGEkIQ4s8tID6MsBAK1IV1XPzNzpeanwPtUqRZojiUuMYnR6
        cSS8ckWXp/EQAP4t6x/pSPtsMSJ0k/kNrKC70KfVlJFIEnZjbZA17ue8ALgzBGmu
        0WAWCSsGAQQB2kcPAQEHQBxpkLVz4yvM7io7W+4Xo7Y86hD1srAdR9nHF1NIoMU8
        iH4EGBYKACYWIQTb9LpVOL9FVePoVI6Pbwk2452dDgUCaa7RYAIbIAUJAeBhkAAK
        CRCPbwk2452dDud/AP9muWh2fNzF3yDDUtT2Wk1YjqqXemxWRU/47leyzoDykgEA
        +DPyJlSs/mqGuZ/wsVFsn3Nuy3D/KWBrzc6Kp0bd2Ag=
        =qSSq
        -----END PGP PUBLIC KEY BLOCK-----
