apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: jira-home
    namespace: atlassian
spec:
    storageClassName: rook-ceph-block
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi
