apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: openspeedtest
    namespace: chaos-openspeedtest
spec:
    interval: 24h
    url: https://openspeedtest.github.io/Helm-chart/
